version: "3.3"

services: 
  telegraf:
    #image: drpsychick/telegraf
    image: telegraf
    container_name: "telegraf"
    network_mode: "bridge"
    ports:
      - "161:161"
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      TEL_AGENT_HOSTNAME: hostname = "asgard.local"
      TEL_OUTPUTS_INFLUXDB_0: "[[outputs.influxdb]]"
      TEL_OUTPUTS_INFLUXDB_URLS: urls = ["http://influxdb.asgard.local"]
      TEL_INPUTS_KERNEL_0: "[[inputs.kernel]]"
      TEL_INPUTS_MEM_0: "[[inputs.mem]]"
      TEL_INPUTS_SWAP_0: "[[inputs.swap]]"
      TEL_INPUTS_PROCESSES_0: "[[inputs.processes]]"
      TEL_INPUTS_SYSTEM_0: "[[inputs.system]]"
      TEL_INPUTS_DISK_0: "[[inputs.disk]]"
      TEL_INPUTS_DISKIO_0: "[[inputs.diskio]]"
      TEL_INPUTS_NET_0: "[[inputs.net]]"
      TEL_INPUTS_NETSTAT_0: "[[inputs.netstat]]"
    volumes:
      - "/proc:/rootfs/proc:ro"
      - "/sys:/rootfs/sys:ro"
      - "/etc:/rootfs/etc:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro" #get docker metrics
      - "/home/abacus/docker_compose/tig/conf/telegraf:/etc/telegraf:ro" #config
      - "/usr/share/snmp/mibs:/usr/share/snmp/mibs:ro" #snmp package tables 
      #- "/var/run/docker.sock:/var/run/docker.sock:ro"
    #cpu_percent: 1
    #mem_limit: 50m
    restart: always
  
  influxdb:
    image: drpsychick/influxdb
    container_name: "influsdb"
    network_mode: "bridge"
    environment:
      IFX_GLOBAL: reporting-disabled = true
      INFLUXDB_HTTP_BIND_ADDRESS: ":8086"
    ports:
      #- 8086:8086
      - 8089:8089/udp
    expose:
      - "8086"
    volumes:
      - "influxdb:/var/lib/influxdb"
    #cpu_percent: 50
    #mem_limit: 1g
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.asgard.local`)"
      - "traefik.http.routers.influxdb.entrypoints=web"

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    network_mode: "bridge"
    #environment:
      #GF_INSTALL_PLUGINS: # plugins to install
    expose:
      - "3000"
    volumes:
      - "grafana:/var/lib/grafana"
    #cpu_percent: 1
    #mem_limit: 200m
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.rule=Host(`grafana.asgard.local`)"
      - "traefik.http.routers.grafana.entrypoints=web"

volumes:
  influxdb:
  grafana:
